language: generic
sudo: required
services:
  - docker
before_install: 
  - docker build -t vijayrao/multipledockertesti -f ./client/Dockerfile.dev ./client

script: 
  - docker run  -e CI=true vijayrao/multipledockertesti npm run test -- --coverage

after_success: 
  - docker build -t vijayrao/multi-client ./client
  - docker build -t vijayrao/multi-nginx ./nginx
  - docker build -t vijayrao/multi-server ./server
  - docker build -t vijayrao/multi-worker ./worker
